/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpf_com_testlauncher_TestNDK */

#ifndef _Included_cpf_com_testlauncher_test_ndk_TestNDK
#define _Included_cpf_com_testlauncher_test_ndk_TestNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpf_com_testlauncher_TestNDK
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring; JNICALL Java_cpf_com_testlauncher_test_ndk_TestNDK_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
